services:
  pulscare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulscare-site
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.pulscare.rule=Host(`pulscare.ru`) || Host(`www.pulscare.ru`) || Host(`pulsezaboty.ru`) || Host(`www.pulsezaboty.ru`)"
      - "traefik.http.routers.pulscare.entrypoints=websecure"
      - "traefik.http.routers.pulscare.tls.certresolver=myresolver"
      - "traefik.http.routers.pulscare.priority=10"
      - "traefik.http.services.pulscare.loadbalancer.server.port=3001"
    networks:
      - default
      - traefik_network

networks:
  traefik_network:
    external: true
